// Liberte menü verisi — Excel'den otomatik üretildi. Elle düzenlemeyin; scripts/import-menu-from-xlsx.mjs kullanın.
export const MENU_REVISION = 1;

export const menuCategories = [
  {
    "id": 1,
    "name": "Sıcak Kahve",
    "description": "Espresso Bazlı Sıcak Kahveler",
    "icon": "☕"
  },
  {
    "id": 2,
    "name": "Tatlılar",
    "description": "Tatlılar",
    "icon": "🍰"
  },
  {
    "id": 3,
    "name": "Soğuk Kahve",
    "description": "Espresso Bazlı Soğuk Kahveler",
    "icon": "🧊"
  },
  {
    "id": 4,
    "name": "Sıcak İçecek",
    "description": "Sıcak İçecekler",
    "icon": "🍵"
  },
  {
    "id": 5,
    "name": "Sandviç",
    "description": "Sandvic Çeşitleri",
    "icon": "🥪"
  },
  {
    "id": 6,
    "name": "Burger",
    "description": "Hamburger Çeşitleri",
    "icon": "🍔"
  },
  {
    "id": 7,
    "name": "Soğuk İçecek",
    "description": "Soğuk İçecekler",
    "icon": "🥤"
  }
];

export const menuItems = [
  {
    "id": 1,
    "categoryId": 1,
    "name": "Americano",
    "description": "Espressonun sıcak suyla yumuşatıldığı sade, hafif ve uzun içimli kahve seçeneği. Temiz ve net lezzet.",
    "price": 150,
    "featured": false,
    "best": false,
    "image": "☕",
    "tone": "#b69474",
    "imageUrl": ""
  },
  {
    "id": 2,
    "categoryId": 1,
    "name": "Cappuccino",
    "description": "Yoğun espresso, sıcak süt ve süt köpüğünün mükemmel dengesi. Klasik ve dengeli bir kahve keyfi.",
    "price": 150,
    "featured": false,
    "best": false,
    "image": "☕",
    "tone": "#b69474",
    "imageUrl": ""
  },
  {
    "id": 3,
    "categoryId": 1,
    "name": "Caramel Latte",
    "description": "Yoğun espresso ve bol sütle hazırlanan, yumuşak içimli klasik kahve lezzeti. Günün her anına yakışır.",
    "price": 170,
    "featured": false,
    "best": false,
    "image": "☕",
    "tone": "#b69474",
    "imageUrl": ""
  },
  {
    "id": 4,
    "categoryId": 1,
    "name": "Caramel Macchiato",
    "description": "Vanilyalı süt üzerine dökülen espresso ve karamel sos ile hazırlanan, katmanlı ve tatlı bir kahve deneyimi.",
    "price": 170,
    "featured": false,
    "best": false,
    "image": "☕",
    "tone": "#b69474",
    "imageUrl": ""
  },
  {
    "id": 5,
    "categoryId": 1,
    "name": "Cortado",
    "description": "Eşit oranlarda espresso ve sıcak sütle hazırlanan, yoğun ve dengeli bir kahve seçeneği. Az köpüklü ve net aromalı.",
    "price": 130,
    "featured": false,
    "best": false,
    "image": "☕",
    "tone": "#b69474",
    "imageUrl": ""
  },
  {
    "id": 6,
    "categoryId": 1,
    "name": "Double Esspresso",
    "description": "İki shot yoğun ve aromatik espresso. Güçlü kahve sevenler için saf ve net bir lezzet.",
    "price": 100,
    "featured": false,
    "best": false,
    "image": "☕",
    "tone": "#b69474",
    "imageUrl": ""
  },
  {
    "id": 7,
    "categoryId": 1,
    "name": "Fındıklı Latte",
    "description": "Yoğun espresso ve bol sütle hazırlanan, yumuşak içimli klasik kahve lezzeti. Günün her anına yakışır.",
    "price": 170,
    "featured": false,
    "best": false,
    "image": "☕",
    "tone": "#b69474",
    "imageUrl": ""
  },
  {
    "id": 8,
    "categoryId": 1,
    "name": "Filtre Kahve",
    "description": "Demlenerek hazırlanan sade, yumuşak ve uzun içimli kahve. Gün boyu keyifle tüketilebilir klasik bir lezzet.",
    "price": 140,
    "featured": false,
    "best": false,
    "image": "☕",
    "tone": "#b69474",
    "imageUrl": ""
  },
  {
    "id": 9,
    "categoryId": 1,
    "name": "Flat White",
    "description": "Yoğun espresso ve ince mikro köpüklü sütle hazırlanan, dengeli ve pürüzsüz içimli kahve tercihi.",
    "price": 170,
    "featured": false,
    "best": false,
    "image": "☕",
    "tone": "#b69474",
    "imageUrl": ""
  },
  {
    "id": 10,
    "categoryId": 1,
    "name": "Gold Mocha",
    "description": "Beyaz çikolata, espresso ve karamelli dokunuşlarla zenginleştirilmiş özel mocha tarifi. Lüks ve tatlı bir kahve keyfi.",
    "price": 180,
    "featured": false,
    "best": false,
    "image": "☕",
    "tone": "#b69474",
    "imageUrl": ""
  },
  {
    "id": 11,
    "categoryId": 1,
    "name": "Latte",
    "description": "Yoğun espresso ve bol sütle hazırlanan, yumuşak içimli klasik kahve lezzeti. Günün her anına yakışır.",
    "price": 150,
    "featured": false,
    "best": false,
    "image": "☕",
    "tone": "#b69474",
    "imageUrl": ""
  },
  {
    "id": 12,
    "categoryId": 1,
    "name": "Macchiato",
    "description": "Yoğun espresso üzerine hafif süt köpüğü eklenerek hazırlanan kısa ve karakteristik bir kahve. Sert ve aromatik.",
    "price": 150,
    "featured": false,
    "best": false,
    "image": "☕",
    "tone": "#b69474",
    "imageUrl": ""
  },
  {
    "id": 13,
    "categoryId": 1,
    "name": "Mocha",
    "description": "Espresso, süt ve çikolatanın uyumuyla hazırlanan zengin, tatlı ve yoğun aromalı kahve keyfi.",
    "price": 170,
    "featured": false,
    "best": false,
    "image": "☕",
    "tone": "#b69474",
    "imageUrl": ""
  },
  {
    "id": 14,
    "categoryId": 1,
    "name": "Salted Caramel Latte",
    "description": "Yoğun espresso ve bol sütle hazırlanan, yumuşak içimli klasik kahve lezzeti. Günün her anına yakışır.",
    "price": 170,
    "featured": false,
    "best": false,
    "image": "☕",
    "tone": "#b69474",
    "imageUrl": ""
  },
  {
    "id": 15,
    "categoryId": 1,
    "name": "Sütlü Filtre",
    "description": "Demlenmiş filtre kahve ve sıcak sütün buluştuğu sade, dengeli ve yumuşak içimli kahve keyfi.",
    "price": 150,
    "featured": false,
    "best": false,
    "image": "☕",
    "tone": "#b69474",
    "imageUrl": ""
  },
  {
    "id": 16,
    "categoryId": 1,
    "name": "Toffeenut Latte",
    "description": "Yoğun espresso ve bol sütle hazırlanan, yumuşak içimli klasik kahve lezzeti. Günün her anına yakışır.",
    "price": 170,
    "featured": false,
    "best": false,
    "image": "☕",
    "tone": "#b69474",
    "imageUrl": ""
  },
  {
    "id": 17,
    "categoryId": 1,
    "name": "Vanilya Latte",
    "description": "Yoğun espresso ve bol sütle hazırlanan, yumuşak içimli klasik kahve lezzeti. Günün her anına yakışır.",
    "price": 170,
    "featured": false,
    "best": false,
    "image": "☕",
    "tone": "#b69474",
    "imageUrl": ""
  },
  {
    "id": 18,
    "categoryId": 1,
    "name": "White Mocha",
    "description": "Beyaz çikolata, espresso ve sütle buluşarak tatlı ve kremsi bir kahve keyfi sunar. Zarif ve yumuşak içimli.",
    "price": 170,
    "featured": false,
    "best": false,
    "image": "☕",
    "tone": "#b69474",
    "imageUrl": ""
  },
  {
    "id": 19,
    "categoryId": 2,
    "name": "Cheesecake",
    "description": "Kremamsı dokusu ve çıtır tabanıyla enfes bir klasik. Her lokmada tatlı bir kaçamak.",
    "price": 240,
    "featured": false,
    "best": false,
    "image": "🍰",
    "tone": "#d6ad70",
    "imageUrl": ""
  },
  {
    "id": 20,
    "categoryId": 2,
    "name": "Cheesecake Frambuaz",
    "description": "Kremamsı dokusu ve çıtır tabanıyla enfes bir klasik. Her lokmada tatlı bir kaçamak.",
    "price": 240,
    "featured": false,
    "best": false,
    "image": "🍰",
    "tone": "#d6ad70",
    "imageUrl": ""
  },
  {
    "id": 21,
    "categoryId": 2,
    "name": "Cheesecake Limonlu",
    "description": "Kremamsı dokusu ve çıtır tabanıyla enfes bir klasik. Her lokmada tatlı bir kaçamak.",
    "price": 240,
    "featured": false,
    "best": false,
    "image": "🍰",
    "tone": "#d6ad70",
    "imageUrl": ""
  },
  {
    "id": 22,
    "categoryId": 2,
    "name": "Cheesecake Lotus",
    "description": "Kremamsı dokusu ve çıtır tabanıyla enfes bir klasik. Her lokmada tatlı bir kaçamak.",
    "price": 270,
    "featured": false,
    "best": false,
    "image": "🍰",
    "tone": "#d6ad70",
    "imageUrl": ""
  },
  {
    "id": 23,
    "categoryId": 2,
    "name": "ÇİKOLATALI COOKİE PİE",
    "description": "ÇİKOLATALI COOKİE PİE",
    "price": 250,
    "featured": false,
    "best": false,
    "image": "🍰",
    "tone": "#d6ad70",
    "imageUrl": ""
  },
  {
    "id": 24,
    "categoryId": 2,
    "name": "LİBERTE BROWNİ",
    "description": "LİBERTE BROWNİ",
    "price": 260,
    "featured": false,
    "best": false,
    "image": "🍰",
    "tone": "#d6ad70",
    "imageUrl": ""
  },
  {
    "id": 25,
    "categoryId": 2,
    "name": "Liberte Cream Puff",
    "description": "Liberte Cream Puff",
    "price": 150,
    "featured": false,
    "best": false,
    "image": "🍰",
    "tone": "#d6ad70",
    "imageUrl": ""
  },
  {
    "id": 26,
    "categoryId": 2,
    "name": "Liberte Cream Puff Belçika Çikoatası",
    "description": "Liberte Cream Puff Belçika Çikoatası",
    "price": 50,
    "featured": false,
    "best": false,
    "image": "🍰",
    "tone": "#d6ad70",
    "imageUrl": ""
  },
  {
    "id": 27,
    "categoryId": 2,
    "name": "Magnolia",
    "description": "Kat kat bisküvi, krema ve taze meyvelerle hazırlanan hafif ve lezzetli soğuk tatlı. Her kaşıkta yumuşak bir mutluluk.",
    "price": 200,
    "featured": false,
    "best": false,
    "image": "🍰",
    "tone": "#d6ad70",
    "imageUrl": ""
  },
  {
    "id": 28,
    "categoryId": 2,
    "name": "Magnolia Çilek",
    "description": "Kat kat bisküvi, krema ve taze meyvelerle hazırlanan hafif ve lezzetli soğuk tatlı. Her kaşıkta yumuşak bir mutluluk.",
    "price": 200,
    "featured": false,
    "best": false,
    "image": "🍰",
    "tone": "#d6ad70",
    "imageUrl": ""
  },
  {
    "id": 29,
    "categoryId": 2,
    "name": "Magnolia Lotus",
    "description": "Kat kat bisküvi, krema ve taze meyvelerle hazırlanan hafif ve lezzetli soğuk tatlı. Her kaşıkta yumuşak bir mutluluk.",
    "price": 220,
    "featured": false,
    "best": false,
    "image": "🍰",
    "tone": "#d6ad70",
    "imageUrl": ""
  },
  {
    "id": 30,
    "categoryId": 2,
    "name": "Magnolia Muz",
    "description": "Kat kat bisküvi, krema ve taze meyvelerle hazırlanan hafif ve lezzetli soğuk tatlı. Her kaşıkta yumuşak bir mutluluk.",
    "price": 200,
    "featured": false,
    "best": false,
    "image": "🍰",
    "tone": "#d6ad70",
    "imageUrl": ""
  },
  {
    "id": 31,
    "categoryId": 2,
    "name": "San Sebastian",
    "description": "San Sebastian",
    "price": 260,
    "featured": false,
    "best": false,
    "image": "🍰",
    "tone": "#d6ad70",
    "imageUrl": ""
  },
  {
    "id": 32,
    "categoryId": 2,
    "name": "Spoonful",
    "description": "Kat kat dolgulu, kaşıkla yenen özel tatlımız. Her kaşıkta mutluluk saklı.",
    "price": 250,
    "featured": false,
    "best": false,
    "image": "🍰",
    "tone": "#d6ad70",
    "imageUrl": ""
  },
  {
    "id": 33,
    "categoryId": 2,
    "name": "Tiramisu",
    "description": "Kahve aromalı, mascarpone kremasıyla hazırlanmış yumuşak ve hafif İtalyan tatlısı.",
    "price": 210,
    "featured": false,
    "best": false,
    "image": "🍰",
    "tone": "#d6ad70",
    "imageUrl": ""
  },
  {
    "id": 34,
    "categoryId": 2,
    "name": "Waffle",
    "description": "Dışı çıtır, içi yumuşak hamur üzerine çikolata, meyve ve renkli süslemelerle hazırlanan tatlı şöleni.",
    "price": 260,
    "featured": false,
    "best": false,
    "image": "🍰",
    "tone": "#d6ad70",
    "imageUrl": ""
  },
  {
    "id": 35,
    "categoryId": 3,
    "name": "Ice Americano",
    "description": "Yoğun espresso ve soğuk suyla hazırlanan sade ve ferahlatıcı bir kahve klasiği.",
    "price": 160,
    "featured": false,
    "best": false,
    "image": "☕",
    "tone": "#4b8aa8",
    "imageUrl": ""
  },
  {
    "id": 36,
    "categoryId": 3,
    "name": "Ice Caramel Macchiato",
    "description": "Buz üzerinde vanilyalı süt ve espresso katmanları, karamel sosla taçlanmış şık ve lezzetli bir içim.",
    "price": 180,
    "featured": false,
    "best": false,
    "image": "☕",
    "tone": "#4b8aa8",
    "imageUrl": ""
  },
  {
    "id": 37,
    "categoryId": 3,
    "name": "Ice Filtre",
    "description": "Demlenmiş filtre kahvenin buzla buluştuğu sade, hafif ve ferah bir kahve alternatifi.",
    "price": 160,
    "featured": false,
    "best": false,
    "image": "☕",
    "tone": "#4b8aa8",
    "imageUrl": ""
  },
  {
    "id": 38,
    "categoryId": 3,
    "name": "Ice Flat White",
    "description": "Yoğun espresso ve kadifemsi süt dokusunun buzla buluştuğu dengeli ve şık bir kahve deneyimi.",
    "price": 180,
    "featured": false,
    "best": false,
    "image": "☕",
    "tone": "#4b8aa8",
    "imageUrl": ""
  },
  {
    "id": 39,
    "categoryId": 3,
    "name": "Ice Latte",
    "description": "Espresso ve soğuk sütün buzla birleştiği hafif, yumuşak içimli serin bir kahve klasiği.",
    "price": 170,
    "featured": false,
    "best": false,
    "image": "☕",
    "tone": "#4b8aa8",
    "imageUrl": ""
  },
  {
    "id": 40,
    "categoryId": 3,
    "name": "Ice Mocha",
    "description": "Espresso, süt ve çikolatanın buzla buluştuğu tatlı ve enerjik bir kahve keyfi.",
    "price": 180,
    "featured": false,
    "best": false,
    "image": "☕",
    "tone": "#4b8aa8",
    "imageUrl": ""
  },
  {
    "id": 41,
    "categoryId": 3,
    "name": "Ice White Mocha",
    "description": "Beyaz çikolata soslu, sütlü ve buzlu kahve karışımı. Tatlı severler için zarif bir seçenek.",
    "price": 180,
    "featured": false,
    "best": false,
    "image": "☕",
    "tone": "#4b8aa8",
    "imageUrl": ""
  },
  {
    "id": 42,
    "categoryId": 3,
    "name": "İce Caramel Latte",
    "description": "Espresso ve soğuk sütün buzla birleştiği hafif, yumuşak içimli serin bir kahve klasiği.",
    "price": 180,
    "featured": false,
    "best": false,
    "image": "☕",
    "tone": "#4b8aa8",
    "imageUrl": ""
  },
  {
    "id": 43,
    "categoryId": 3,
    "name": "İce Fındıklı Latte",
    "description": "Espresso ve soğuk sütün buzla birleştiği hafif, yumuşak içimli serin bir kahve klasiği.",
    "price": 180,
    "featured": false,
    "best": false,
    "image": "☕",
    "tone": "#4b8aa8",
    "imageUrl": ""
  },
  {
    "id": 44,
    "categoryId": 3,
    "name": "İce Matcha Latte",
    "description": "İce Matcha Latte",
    "price": 220,
    "featured": false,
    "best": false,
    "image": "☕",
    "tone": "#4b8aa8",
    "imageUrl": ""
  },
  {
    "id": 45,
    "categoryId": 3,
    "name": "İce Matcha Latte Çilekli Matcha",
    "description": "İce Matcha Latte Çilekli Matcha",
    "price": 240,
    "featured": false,
    "best": false,
    "image": "☕",
    "tone": "#4b8aa8",
    "imageUrl": ""
  },
  {
    "id": 46,
    "categoryId": 3,
    "name": "İce Matcha Latte Matcha",
    "description": "İce Matcha Latte Matcha",
    "price": 220,
    "featured": false,
    "best": false,
    "image": "☕",
    "tone": "#4b8aa8",
    "imageUrl": ""
  },
  {
    "id": 47,
    "categoryId": 3,
    "name": "ice Salted Caramel Latte",
    "description": "Espresso ve soğuk sütün buzla birleştiği hafif, yumuşak içimli serin bir kahve klasiği.",
    "price": 180,
    "featured": false,
    "best": false,
    "image": "☕",
    "tone": "#4b8aa8",
    "imageUrl": ""
  },
  {
    "id": 48,
    "categoryId": 3,
    "name": "İce Toffeenut Latte",
    "description": "Espresso ve soğuk sütün buzla birleştiği hafif, yumuşak içimli serin bir kahve klasiği.",
    "price": 180,
    "featured": false,
    "best": false,
    "image": "☕",
    "tone": "#4b8aa8",
    "imageUrl": ""
  },
  {
    "id": 49,
    "categoryId": 3,
    "name": "İce Vanilya Latte",
    "description": "Espresso ve soğuk sütün buzla birleştiği hafif, yumuşak içimli serin bir kahve klasiği.",
    "price": 180,
    "featured": false,
    "best": false,
    "image": "☕",
    "tone": "#4b8aa8",
    "imageUrl": ""
  },
  {
    "id": 50,
    "categoryId": 4,
    "name": "Bardak Çay",
    "description": "Taze demlenmiş klasik Türk çayı, ince belli bardakta servis edilir. Her yudumda geleneksel lezzet.",
    "price": 35,
    "featured": false,
    "best": false,
    "image": "🍵",
    "tone": "#8b6914",
    "imageUrl": ""
  },
  {
    "id": 51,
    "categoryId": 4,
    "name": "Beyaz Sıcak Çikolata",
    "description": "Yoğun aromalı beyaz çikolata ile hazırlanmış, kremamsı ve yumuşak içimli sıcak lezzet.",
    "price": 130,
    "featured": false,
    "best": false,
    "image": "🍵",
    "tone": "#8b6914",
    "imageUrl": ""
  },
  {
    "id": 52,
    "categoryId": 4,
    "name": "ÇİLEKLİ TÜRK KAHVESİ",
    "description": "ÇİLEKLİ TÜRK KAHVESİ",
    "price": 120,
    "featured": false,
    "best": false,
    "image": "🍵",
    "tone": "#8b6914",
    "imageUrl": ""
  },
  {
    "id": 53,
    "categoryId": 4,
    "name": "DAMLA SAKIZLI TÜRK KAHVESİ",
    "description": "DAMLA SAKIZLI TÜRK KAHVESİ",
    "price": 120,
    "featured": false,
    "best": false,
    "image": "🍵",
    "tone": "#8b6914",
    "imageUrl": ""
  },
  {
    "id": 54,
    "categoryId": 4,
    "name": "Double Türk Kahvesi",
    "description": "Double Türk Kahvesi",
    "price": 140,
    "featured": false,
    "best": false,
    "image": "🍵",
    "tone": "#8b6914",
    "imageUrl": ""
  },
  {
    "id": 55,
    "categoryId": 4,
    "name": "Fincan Çay",
    "description": "Özenle demlenmiş Türk çayı, porselen fincanda sunulur. Daha yoğun ve sıcak çay keyfi.",
    "price": 60,
    "featured": false,
    "best": false,
    "image": "🍵",
    "tone": "#8b6914",
    "imageUrl": ""
  },
  {
    "id": 56,
    "categoryId": 4,
    "name": "Hibiscus Çayı",
    "description": "Canlandırıcı ekşimsi tadı ve canlı rengiyle, soğuk ya da sıcak tüketilebilen bitki çayı. Doğal ve ferahlatıcı.",
    "price": 140,
    "featured": false,
    "best": false,
    "image": "🍵",
    "tone": "#8b6914",
    "imageUrl": ""
  },
  {
    "id": 57,
    "categoryId": 4,
    "name": "Kış Çayı",
    "description": "Tarçın, karanfil, zencefil ve meyve notalarıyla harmanlanmış, içinizi ısıtan doğal bitki çayı karışımı.",
    "price": 140,
    "featured": false,
    "best": false,
    "image": "🍵",
    "tone": "#8b6914",
    "imageUrl": ""
  },
  {
    "id": 58,
    "categoryId": 4,
    "name": "Nane Limon Çayı",
    "description": "Taze nane ve limonun sıcak suyla buluştuğu, rahatlatıcı ve doğal bir içecek.",
    "price": 140,
    "featured": false,
    "best": false,
    "image": "🍵",
    "tone": "#8b6914",
    "imageUrl": ""
  },
  {
    "id": 59,
    "categoryId": 4,
    "name": "Osmanlı Dibek Kahvesi",
    "description": "Geleneksel dibek taşında dövülerek hazırlanan, yumuşak içimli ve aromatik bir Osmanlı kahvesi lezzeti.",
    "price": 120,
    "featured": false,
    "best": false,
    "image": "🍵",
    "tone": "#8b6914",
    "imageUrl": ""
  },
  {
    "id": 60,
    "categoryId": 4,
    "name": "Sahlep",
    "description": "Gerçek salep tozuyla hazırlanan sıcak ve yoğun kış lezzeti. Tarçınla birlikte sunulur.",
    "price": 140,
    "featured": false,
    "best": false,
    "image": "🍵",
    "tone": "#8b6914",
    "imageUrl": ""
  },
  {
    "id": 61,
    "categoryId": 4,
    "name": "Sıcak Çikolata",
    "description": "Yoğun kakao tadı ve kremamsı yapısıyla iç ısıtan, tatlı bir klasik.",
    "price": 140,
    "featured": false,
    "best": false,
    "image": "🍵",
    "tone": "#8b6914",
    "imageUrl": ""
  },
  {
    "id": 62,
    "categoryId": 4,
    "name": "Türk Kahvesi",
    "description": "Kendine özgü pişirme yöntemi ve telvesiyle sunulan, yoğun aromalı geleneksel kahve klasiği.",
    "price": 90,
    "featured": false,
    "best": false,
    "image": "🍵",
    "tone": "#8b6914",
    "imageUrl": ""
  },
  {
    "id": 63,
    "categoryId": 4,
    "name": "Yeşil Çay",
    "description": "Yeşil Çay",
    "price": 140,
    "featured": false,
    "best": false,
    "image": "🍵",
    "tone": "#8b6914",
    "imageUrl": ""
  },
  {
    "id": 64,
    "categoryId": 5,
    "name": "Liberte Sandvic Ajvar",
    "description": "Özel ciabatta ekmeğinde ajvar sosu,roka,kaşar peynir,hindi füme ve domates ile servis edilir",
    "price": 250,
    "featured": false,
    "best": false,
    "image": "🥪",
    "tone": "#c4a035",
    "imageUrl": ""
  },
  {
    "id": 65,
    "categoryId": 5,
    "name": "Liberte Sandvic Pesto",
    "description": "Özel ciabatta ekmeğinde pesto sosu,roka,kaşar peynir,hindi füme ve domates ile servis edilir",
    "price": 250,
    "featured": false,
    "best": false,
    "image": "🥪",
    "tone": "#c4a035",
    "imageUrl": ""
  },
  {
    "id": 66,
    "categoryId": 6,
    "name": "100 Gram Dana Kıyma",
    "description": "100 Gram Dana Kıyma,Soğan,Cheddar Peynir,Özel Burger Sosu Ve Patates Kızartması ile servis edilir.",
    "price": 360,
    "featured": true,
    "best": true,
    "image": "🍔",
    "tone": "#a0482d",
    "imageUrl": ""
  },
  {
    "id": 67,
    "categoryId": 6,
    "name": "150 Gram Dana Kıyma",
    "description": "100 Gram Dana Kıyma,Soğan,Cheddar Peynir,Özel Burger Sosu Ve Patates Kızartması ile servis edilir.",
    "price": 395,
    "featured": true,
    "best": true,
    "image": "🍔",
    "tone": "#a0482d",
    "imageUrl": ""
  },
  {
    "id": 68,
    "categoryId": 6,
    "name": "Patates Tabağı",
    "description": "Patates Tabağı",
    "price": 120,
    "featured": false,
    "best": false,
    "image": "🍟",
    "tone": "#a0482d",
    "imageUrl": ""
  },
  {
    "id": 69,
    "categoryId": 6,
    "name": "Smash Burger",
    "description": "100 Gram Dana Kıyma,Soğan,Cheddar Peynir,Özel Burger Sosu Ve Patates Kızartması ile servis edilir.",
    "price": 360,
    "featured": true,
    "best": true,
    "image": "🍔",
    "tone": "#a0482d",
    "imageUrl": ""
  },
  {
    "id": 70,
    "categoryId": 6,
    "name": "Vişne Tulum Burger",
    "description": "140 Gram Dana Kıyma,Erzincan Tulum Peynir,Doğal Vişne Reçeli ile servis edilir.",
    "price": 395,
    "featured": true,
    "best": true,
    "image": "🍔",
    "tone": "#a0482d",
    "imageUrl": ""
  },
  {
    "id": 71,
    "categoryId": 7,
    "name": "Buzdağı Exclusive Su",
    "description": "Doğal kaynaklardan gelen özel şişe suyu, saf ve berrak içimiyle.",
    "price": 20,
    "featured": false,
    "best": false,
    "image": "🥤",
    "tone": "#5ba3c6",
    "imageUrl": ""
  },
  {
    "id": 72,
    "categoryId": 7,
    "name": "Churchill",
    "description": "Sade maden suyu, limon ve tuzun ferahlatıcı birleşimi. Klasik ve canlandırıcı bir içecek.",
    "price": 110,
    "featured": false,
    "best": false,
    "image": "🥤",
    "tone": "#5ba3c6",
    "imageUrl": ""
  },
  {
    "id": 73,
    "categoryId": 7,
    "name": "Coca-Cola",
    "description": "Efsanevi lezzeti ve serinletici gazıyla klasik kola keyfi.",
    "price": 70,
    "featured": false,
    "best": false,
    "image": "🥤",
    "tone": "#5ba3c6",
    "imageUrl": ""
  },
  {
    "id": 74,
    "categoryId": 7,
    "name": "Cool Lime",
    "description": "Taze lime dilimleriyle hazırlanan, nane aromalı ferahlatıcı yaz içeceği. Serinlik her yudumda.",
    "price": 180,
    "featured": false,
    "best": false,
    "image": "🥤",
    "tone": "#5ba3c6",
    "imageUrl": ""
  },
  {
    "id": 75,
    "categoryId": 7,
    "name": "Çarkıfelek",
    "description": "Çarkıfelek",
    "price": 160,
    "featured": false,
    "best": false,
    "image": "🥤",
    "tone": "#5ba3c6",
    "imageUrl": ""
  },
  {
    "id": 76,
    "categoryId": 7,
    "name": "Fanta",
    "description": "Portakal aromasıyla öne çıkan, bol köpüklü ve ferah gazlı içecek klasiği.",
    "price": 70,
    "featured": false,
    "best": false,
    "image": "🥤",
    "tone": "#5ba3c6",
    "imageUrl": ""
  },
  {
    "id": 77,
    "categoryId": 7,
    "name": "Frozen",
    "description": "Frozen",
    "price": 180,
    "featured": false,
    "best": false,
    "image": "🥤",
    "tone": "#5ba3c6",
    "imageUrl": ""
  },
  {
    "id": 78,
    "categoryId": 7,
    "name": "Frozen Çilek",
    "description": "Frozen Çilek",
    "price": 160,
    "featured": false,
    "best": false,
    "image": "🥤",
    "tone": "#5ba3c6",
    "imageUrl": ""
  },
  {
    "id": 79,
    "categoryId": 7,
    "name": "Frozen Mango",
    "description": "Frozen Mango",
    "price": 160,
    "featured": false,
    "best": false,
    "image": "🥤",
    "tone": "#5ba3c6",
    "imageUrl": ""
  },
  {
    "id": 80,
    "categoryId": 7,
    "name": "Fuse Tea Şeftali",
    "description": "Demlenmiş çay ve şeftalinin uyumuyla hafif, meyvemsi ve ferah bir içecek.",
    "price": 70,
    "featured": false,
    "best": false,
    "image": "🥤",
    "tone": "#5ba3c6",
    "imageUrl": ""
  },
  {
    "id": 81,
    "categoryId": 7,
    "name": "Liberte Hibiscus",
    "description": "Hibiscus çiçeğiyle hazırlanan özel tarifimiz; canlı rengi, hafif ekşi tadı ve ferahlatıcı etkisiyle bambaşka.",
    "price": 180,
    "featured": false,
    "best": false,
    "image": "🥤",
    "tone": "#5ba3c6",
    "imageUrl": ""
  },
  {
    "id": 82,
    "categoryId": 7,
    "name": "Liberte Special",
    "description": "Barista misafirin istediği tada en uygun kokteyli özel olarak hazırlar.",
    "price": 200,
    "featured": false,
    "best": false,
    "image": "🥤",
    "tone": "#5ba3c6",
    "imageUrl": ""
  },
  {
    "id": 83,
    "categoryId": 7,
    "name": "Limonata",
    "description": "Taze limon suyu ve doğal şekerle hazırlanan, ev yapımı ferahlatıcı klasik.",
    "price": 120,
    "featured": false,
    "best": false,
    "image": "🥤",
    "tone": "#5ba3c6",
    "imageUrl": ""
  },
  {
    "id": 84,
    "categoryId": 7,
    "name": "Limonata Çilek",
    "description": "Taze limon suyu ve doğal şekerle hazırlanan, ev yapımı ferahlatıcı klasik.",
    "price": 130,
    "featured": false,
    "best": false,
    "image": "🥤",
    "tone": "#5ba3c6",
    "imageUrl": ""
  },
  {
    "id": 85,
    "categoryId": 7,
    "name": "Limonata Nane",
    "description": "Taze limon suyu ve doğal şekerle hazırlanan, ev yapımı ferahlatıcı klasik.",
    "price": 130,
    "featured": false,
    "best": false,
    "image": "🥤",
    "tone": "#5ba3c6",
    "imageUrl": ""
  },
  {
    "id": 86,
    "categoryId": 7,
    "name": "Lipton İce Tea",
    "description": "Demlenmiş çay ferahlığı ve meyve aromalarının serinletici buluşması. Soğuk çay keyfi.",
    "price": 70,
    "featured": false,
    "best": false,
    "image": "🥤",
    "tone": "#5ba3c6",
    "imageUrl": ""
  },
  {
    "id": 87,
    "categoryId": 7,
    "name": "Maden Suyu",
    "description": "Doğal mineralli ve ferahlatıcı içecek, saf maden suyu lezzetiyle.",
    "price": 50,
    "featured": false,
    "best": false,
    "image": "🥤",
    "tone": "#5ba3c6",
    "imageUrl": ""
  },
  {
    "id": 88,
    "categoryId": 7,
    "name": "Maden Suyu Sade",
    "description": "Doğal mineralli ve ferahlatıcı içecek, saf maden suyu lezzetiyle.",
    "price": 50,
    "featured": false,
    "best": false,
    "image": "🥤",
    "tone": "#5ba3c6",
    "imageUrl": ""
  },
  {
    "id": 89,
    "categoryId": 7,
    "name": "Mango Passion",
    "description": "Mango ve orman meyvelerinin mükemmel uyumu.. Serinletici lezzet..",
    "price": 180,
    "featured": false,
    "best": false,
    "image": "🥤",
    "tone": "#5ba3c6",
    "imageUrl": ""
  },
  {
    "id": 90,
    "categoryId": 7,
    "name": "Meyveli Soda Çeşitleri",
    "description": "Doğal mineralli ve ferahlatıcı içecek, saf maden suyu lezzetiyle.",
    "price": 60,
    "featured": false,
    "best": false,
    "image": "🥤",
    "tone": "#5ba3c6",
    "imageUrl": ""
  },
  {
    "id": 91,
    "categoryId": 7,
    "name": "Orman Meyveli",
    "description": "Orman Meyveli",
    "price": 160,
    "featured": false,
    "best": false,
    "image": "🥤",
    "tone": "#5ba3c6",
    "imageUrl": ""
  },
  {
    "id": 92,
    "categoryId": 7,
    "name": "Orman Meyvesi",
    "description": "Taze limon suyu ve doğal şekerle hazırlanan, ev yapımı ferahlatıcı klasik.",
    "price": 130,
    "featured": false,
    "best": false,
    "image": "🥤",
    "tone": "#5ba3c6",
    "imageUrl": ""
  }
];
