-- =============================================================================
-- FAZ 3 — En hassas tablolar: backend-only (policy yok = deny anon/authenticated)
-- postgres rolü (DATABASE_URL) BYPASSRLS — API etkilenmez
-- Destructive işlem YOK
-- =============================================================================

ALTER TABLE IF EXISTS customer_pin_auth ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS auth_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS email_codes ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS auth_rate_limits ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS app_error_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS app_state ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS app_state_backups ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS coupon_uses ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS daily_campaigns ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS check_ins ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS wheel_prizes ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS wheel_spins ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS daily_claims ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS first_order_bonuses ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS referrals ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS feedback ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS google_review_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS customer_notes ENABLE ROW LEVEL SECURITY;
