-- 013 - loyalty_events.id identity (BUG-011)
-- Idempotent; skip if serial/identity already present.

DO $$
DECLARE
  seq_name text;
  is_ident text;
  next_id bigint;
BEGIN
  IF to_regclass('public.loyalty_events') IS NULL THEN
    RAISE NOTICE 'loyalty_events missing - skip';
    RETURN;
  END IF;

  SELECT pg_get_serial_sequence('public.loyalty_events', 'id') INTO seq_name;

  SELECT c.is_identity INTO is_ident
  FROM information_schema.columns c
  WHERE c.table_schema = 'public'
    AND c.table_name = 'loyalty_events'
    AND c.column_name = 'id';

  IF seq_name IS NOT NULL OR is_ident IN ('YES', 'ALWAYS', 'BY DEFAULT') THEN
    RAISE NOTICE 'loyalty_events.id already auto - skip';
    RETURN;
  END IF;

  SELECT COALESCE(MAX(id), 0) + 1 INTO next_id FROM public.loyalty_events;
  IF next_id < 1 THEN
    next_id := 1;
  END IF;

  EXECUTE format(
    'ALTER TABLE public.loyalty_events ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (START WITH %s)',
    next_id
  );
END $$;
