import test from 'node:test';
import assert from 'node:assert/strict';
import { existsSync, readFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const read = (rel) => readFileSync(join(root, rel), 'utf8');

test('BUG-007 adminMembers keyset pagination', () => {
  const src = read('api/_lib/handlers/adminMembers.js');
  assert.match(src, /listCustomersPage/);
  assert.match(src, /loadLoyaltyMapLightForIds/);
  assert.match(src, /nextCursor/);
  assert.match(src, /hasMore/);
  assert.doesNotMatch(src, /listAllCustomers\(/);
});

test('BUG-007 customersStore listCustomersPage LIMIT', () => {
  const src = read('api/_lib/customersStore.js');
  assert.match(src, /export async function listCustomersPage/);
  assert.match(src, /WHERE id >/);
  assert.match(src, /LIMIT /);
});

test('BUG-007 client page loop', () => {
  const src = read('src/lib/adminMemberClient.js');
  assert.match(src, /fetchAdminMembersPage/);
  assert.match(src, /nextCursor/);
  assert.match(src, /afterId/);
});

test('BUG-011 loyalty_events identity SQL', () => {
  const sql = read('scripts/sql/013_loyalty_events_identity.sql');
  assert.match(sql, /GENERATED BY DEFAULT AS IDENTITY/);
  assert.doesNotMatch(sql, /DROP TABLE/i);
  assert.doesNotMatch(sql, /TRUNCATE/i);
});

test('BUG-018 drift column SQL + verify script', () => {
  assert.ok(existsSync(join(root, 'scripts/verify-schema-drift.mjs')));
  assert.ok(existsSync(join(root, 'scripts/apply-schema-drift.mjs')));
  const sql = read('scripts/sql/014_schema_drift_columns.sql');
  assert.match(sql, /referred_by/);
  assert.match(sql, /target_type/);
  assert.match(sql, /is_active/);
  assert.match(sql, /uq_daily_claims_customer_type_day/);
});

test('package.json schema drift scripts', () => {
  const pkg = JSON.parse(read('package.json'));
  assert.ok(pkg.scripts['db:verify-schema']);
  assert.ok(pkg.scripts['db:apply-schema-drift']);
});
