import React, {useState, useEffect, useRef} from 'react';
import {createRoot} from 'react-dom/client';
import {QrCode, Coffee, Gift, Bell, ScanLine, Plus, Minus, LogOut, Crown, Home, Menu as MenuIcon, ShieldCheck, Users, Palette, Trash2, Save, Pencil, Image as ImageIcon, PackagePlus, ShoppingBag, Megaphone, Sparkles, Star, UploadCloud} from 'lucide-react';
import {QRCodeCanvas} from 'qrcode.react';
import {Html5Qrcode} from 'html5-qrcode';
import './style.css';

const seed = {
  settings:{stamp_threshold:10,reward_description:'1 Bedava İçecek',cafe_name:'Liberte Gastro Cafe',app_name:'Liberte Club',bg:'#06110d',card:'#102219',accent:'#b9f5d0',font:'Inter',logo:'',hero_title:'Bugünün Favorileri',hero_subtitle:'Kahve, tatlı ve burger keyfi Liberte’de.',promo_text:'QR kartını göster, 10 damgada 1 içecek bizden.',cashier_pin:'5454'},
  customers:[{id:1,phone:'5058665406',name:'Liberte Gastro',isAdmin:true,createdAt:new Date().toLocaleString('tr-TR')}],
  loyalty:{1:{customerId:1,totalStamps:0,availableRewards:0,usedRewards:0,lifetimeStamps:0}},
  categories:[
    {id:1,name:'Sıcak İçecekler',description:'Özenle hazırlanmış sıcak içecekler'},
    {id:2,name:'Soğuk İçecekler',description:'Serinletici soğuk içecekler'},
    {id:3,name:'Kahvaltı',description:'Sabahın enerjisi için kahvaltı seçenekleri'},
    {id:4,name:'Tatlılar',description:'Ev yapımı tatlılar ve pastalar'},
    {id:5,name:'Burger & Atıştırmalık',description:'Liberte lezzetleri'}
  ],
  items:[
    {id:1,categoryId:1,name:'Filtre Kahve',description:'Günlük taze çekilmiş filtre kahve',price:45,featured:true,image:'☕',tone:'#7b4b2a'},
    {id:2,categoryId:1,name:'Espresso',description:'Yoğun ve aromatik espresso',price:40,image:'☕',tone:'#4b2b18'},
    {id:3,categoryId:1,name:'Cappuccino',description:'Espresso, buharla ısıtılmış süt ve süt köpüğü',price:65,featured:true,image:'☕',tone:'#c69b6d'},
    {id:4,categoryId:1,name:'Latte',description:'Espresso ve bol sütlü latte',price:70,image:'🥛',tone:'#d5c0a0'},
    {id:5,categoryId:2,name:'Ice Americano',description:'Buzlu ferah americano',price:70,featured:true,image:'🧊',tone:'#4b8aa8'},
    {id:6,categoryId:2,name:'Ice Latte',description:'Soğuk sütlü espresso',price:80,featured:true,image:'🥤',tone:'#b69474'},
    {id:7,categoryId:2,name:'Çilekli Matcha Latte',description:'Çilek püresi ve matcha dengesi',price:130,featured:true,image:'🍓',tone:'#9bbf7a'},
    {id:8,categoryId:3,name:'Liberte Kahvaltı',description:'Kahvaltı tabağı',price:250,image:'🍳',tone:'#d69c3b'},
    {id:9,categoryId:4,name:'San Sebastian',description:'Kremamsı cheesecake',price:170,featured:true,image:'🍰',tone:'#d6ad70'},
    {id:10,categoryId:4,name:'Çilekli Magnolia',description:'Çilek, krema ve bisküvi katları',price:145,featured:true,image:'🍓',tone:'#d85f71'},
    {id:11,categoryId:4,name:'Lotuslu Magnolia',description:'Lotus kırığı ve özel krema',price:155,image:'🍪',tone:'#b57b42'},
    {id:12,categoryId:4,name:'Waffle',description:'Çıtır waffle ve çikolata sos',price:180,image:'🧇',tone:'#c88b45'},
    {id:13,categoryId:5,name:'Smash Burger',description:'140 g et, cheddar ve özel sos',price:295,featured:true,image:'🍔',tone:'#a0482d'},
    {id:14,categoryId:5,name:'Patates Kızartması',description:'Çıtır patates',price:95,image:'🍟',tone:'#c9a13b'}
  ],
  notifications:[{id:1,title:'Liberte Club Açıldı',body:'QR kartını göster, damgalarını toplamaya başla.',createdAt:new Date().toLocaleString('tr-TR')}],
  history:[]
};

function mergeDb(x){return x?{...seed,...x,settings:{...seed.settings,...x.settings}}:seed}
function load(){try{const x=JSON.parse(localStorage.getItem('liberteDB'));return mergeDb(x)}catch{return seed}}
function save(db){localStorage.setItem('liberteDB',JSON.stringify(db))}
async function loadRemote(){
  try{
    const r=await fetch('/api/state');
    if(!r.ok) return null;
    const j=await r.json();
    return j?.data ? mergeDb(j.data) : null;
  }catch{return null}
}
async function saveRemote(db){
  try{
    await fetch('/api/state',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({data:db})});
  }catch{}
}

const normalize=p=>p.replace(/\D/g,'').replace(/^90/,'').replace(/^0/,'');
function cssVars(settings){return {'--bg':settings.bg,'--card':settings.card,'--accent':settings.accent,'fontFamily':`${settings.font}, Inter, system-ui, Arial`}}

function App(){const [db,setDb]=useState(load); const [session,setSession]=useState(JSON.parse(localStorage.getItem('liberteSession')||'null')); const [tab,setTab]=useState('home'); const [sync,setSync]=useState('local');
 useEffect(()=>{loadRemote().then(remote=>{if(remote){setDb(remote);save(remote);setSync('cloud')}else{setSync('local')}})},[]);
 const commit=n=>{setDb(n);save(n);saveRemote(n);setSync('cloud')};
 if(!session) return <div style={cssVars(db.settings)}><Login db={db} commit={commit} setSession={setSession}/></div>;
 const customer=db.customers.find(c=>c.id===session.customerId); const card=db.loyalty[customer.id]||{totalStamps:0,availableRewards:0,usedRewards:0,lifetimeStamps:0};
 return <div className="app" style={cssVars(db.settings)}><Header db={db} customer={customer} setSession={setSession} sync={sync}/>{tab==='home'&&<HomeScreen db={db} customer={customer} card={card} setTab={setTab}/>} {tab==='qr'&&<QrScreen customer={customer} card={card} db={db}/>} {tab==='menu'&&<MenuScreen db={db}/>} {tab==='campaign'&&<CampaignScreen db={db}/>} {tab==='admin'&&customer.isAdmin&&<AdminScreen db={db} commit={commit}/>}<Nav tab={tab} setTab={setTab} isAdmin={customer.isAdmin}/></div>
}
function BrandLogo({db,small=false}){return db.settings.logo?<img className={small?'brandLogo small':'brandLogo'} src={db.settings.logo}/>:<div className={small?'logo small':'logo'}><span className="logoScript">Liberte</span><em>Gastro Cafe</em></div>}
function Login({db,commit,setSession}){const [phone,setPhone]=useState(''); const [name,setName]=useState(''); const login=()=>{const ph=normalize(phone); if(ph.length<10) return alert('Telefonu 10 hane gir. Örn: 5058665406'); let n={...db,customers:[...db.customers],loyalty:{...db.loyalty}}; let c=n.customers.find(x=>x.phone===ph); if(!c){c={id:Date.now(),phone:ph,name:name||'Liberte Misafiri',isAdmin:false,createdAt:new Date().toLocaleString('tr-TR')}; n.customers.push(c); n.loyalty[c.id]={customerId:c.id,totalStamps:0,availableRewards:0,usedRewards:0,lifetimeStamps:0}; commit(n)} const s={customerId:c.id}; localStorage.setItem('liberteSession',JSON.stringify(s)); setSession(s)}; return <main className="login premiumLogin"><div className="aurora one"></div><div className="aurora two"></div><div className="loginShell"><div className="brand"><BrandLogo db={db}/><p className="eyebrow">Liberte Gastro Cafe</p><h1>{db.settings.app_name}</h1><p>QR sadakat kartın, özel kampanyalar ve menü tek yerde.</p></div><div className="card loginCard"><label>Telefon numarası</label><input value={phone} onChange={e=>setPhone(e.target.value)} placeholder="05xx xxx xx xx" inputMode="tel"/><label>İsim / ünvan</label><input value={name} onChange={e=>setName(e.target.value)} placeholder="Adınız"/><button onClick={login}>Giriş Yap</button></div></div></main>}
function Header({db,customer,setSession,sync}){return <header><div className="headBrand"><BrandLogo db={db} small/><div><b>{db.settings.app_name}</b><span>{customer.name} · {sync==='cloud'?'Bulut kayıt':'Yerel kayıt'}</span></div></div><button className="ghost" onClick={()=>{localStorage.removeItem('liberteSession');setSession(null)}}><LogOut size={18}/></button></header>}
function HomeScreen({db,customer,card,setTab}){const progress=Math.round((card.totalStamps/db.settings.stamp_threshold)*100); return <section><div className="hero bannerGlow premiumHero"><div><p className="eyebrow">Liberte Club</p><h2>{db.settings.hero_title||db.settings.cafe_name}</h2><p>{db.settings.hero_subtitle||db.settings.promo_text}</p></div><Sparkles size={38}/></div><StoryStrip db={db}/><div className="grid"><button onClick={()=>setTab('qr')} className="tile"><QrCode/> QR Kartım</button><button onClick={()=>setTab('menu')} className="tile"><Coffee/> Menü</button><button onClick={()=>setTab('campaign')} className="tile"><Bell/> Kampanyalar</button></div><div className="card stampCard"><div className="sectionHead"><h3>Sadakat Durumu</h3><span>{card.availableRewards} ödül</span></div><div className="stampRow">{Array.from({length:db.settings.stamp_threshold}).map((_,i)=><span key={i} className={i<card.totalStamps?'stamp on':'stamp'}>☕</span>)}</div><div className="bar"><i style={{width:progress+'%'}}/></div><p>{card.totalStamps}/{db.settings.stamp_threshold} damga · {db.settings.reward_description}</p></div><Featured db={db}/></section>}
function StoryStrip({db}){const stories=[['🍔','Smash'],['🍓','Magnolia'],['☕','Kahve'],['🧊','Soğuk'],['🎁','Ödül']]; return <div className="storyStrip">{stories.map(([emoji,label])=><div className="storyBubble" key={label}><span>{emoji}</span><b>{label}</b></div>)}</div>}
function ProductVisual({item,large=false}){const img=item.image||'☕'; const isUrl=String(img).startsWith('http')||String(img).startsWith('data:'); return <div className={large?'productVisual large':'productVisual'} style={{'--tone':item.tone||'#b9f5d0'}}>{isUrl?<img src={img}/>:<span>{img}</span>}</div>}
function ProductCard({item,compact=false}){return <div className={compact?'productCard compact':'productCard'}><ProductVisual item={item}/><div className="productInfo"><div className="productTop"><b>{item.name}</b><span className="favDot"><Star size={13}/></span></div><p>{item.description}</p><div><strong>{item.price}₺</strong>{item.featured&&<em>Popüler</em>}</div></div></div>}
function Featured({db}){const items=db.items.filter(i=>i.featured).slice(0,6); return <div className="card"><div className="sectionHead"><h3>Popüler Lezzetler</h3><span>Favoriler</span></div><div className="featuredRail">{items.map(i=><ProductCard key={i.id} item={i} compact/>)}</div></div>}
function QrScreen({customer,card,db}){const token=`LIBERTE:${customer.id}:${customer.phone}`;return <section><div className="card center qrCardPremium"><BrandLogo db={db} small/><p className="eyebrow">Liberte Sadakat Kartı</p><h2>{customer.name}</h2><div className="qr"><QRCodeCanvas value={token} size={220} bgColor="#ffffff" fgColor="#07110d"/></div><p>Kasada bu kodu göster.</p><div className="rewardPill">{card.totalStamps}/{db.settings.stamp_threshold} damga · {card.availableRewards} ödül</div></div></section>}
function MenuScreen({db}){const [cat,setCat]=useState(db.categories[0]?.id||1); const cats=db.categories; const items=db.items.filter(i=>i.categoryId===cat); const activeCat=cats.find(c=>c.id===cat); return <section><div className="menuHero"><div><p className="eyebrow">Liberte Menü</p><h2>{activeCat?.name||'Menü'}</h2><p>{activeCat?.description||'Güncel ürünler'}</p><small>{db.settings.promo_text}</small></div><Coffee size={42}/></div><div className="chips">{cats.map(c=><button className={cat===c.id?'active':''} onClick={()=>setCat(c.id)} key={c.id}>{c.name}</button>)}</div><div className="productGrid">{items.map(i=><ProductCard key={i.id} item={i}/>)}</div></section>}
function CampaignScreen({db}){return <section><div className="card campaignTop"><Megaphone/><h2>Kampanyalar</h2><p>Admin panelden yayınlanan duyurular burada görünür.</p></div><div className="card">{db.notifications.map(n=><div className="notice campaignNotice" key={n.id}><b>{n.title}</b><p>{n.body}</p><small>{n.createdAt}</small></div>)}</div></section>}

function AdminScreen({db,commit}){const [adminTab,setAdminTab]=useState('design');return <section><div className="adminTitle"><ShieldCheck/><h2>Admin Panel</h2></div><div className="adminTabs"><button className={adminTab==='design'?'active':''} onClick={()=>setAdminTab('design')}><Palette/> Tasarım</button><button className={adminTab==='products'?'active':''} onClick={()=>setAdminTab('products')}><PackagePlus/> Ürünler</button><button className={adminTab==='customers'?'active':''} onClick={()=>setAdminTab('customers')}><Users/> Kullanıcılar</button><button className={adminTab==='loyalty'?'active':''} onClick={()=>setAdminTab('loyalty')}><ScanLine/> Sadakat</button><button className={adminTab==='cashier'?'active':''} onClick={()=>setAdminTab('cashier')}><ShoppingBag/> Kasiyer</button></div>{adminTab==='design'&&<DesignAdmin db={db} commit={commit}/>} {adminTab==='products'&&<ProductAdmin db={db} commit={commit}/>} {adminTab==='customers'&&<CustomerAdmin db={db}/>} {adminTab==='loyalty'&&<LoyaltyAdmin db={db} commit={commit}/>} {adminTab==='cashier'&&<CashierAdmin db={db} commit={commit}/>}</section>}
function DesignAdmin({db,commit}){const [s,setS]=useState(db.settings); const upload=e=>{const f=e.target.files?.[0]; if(!f)return; const r=new FileReader(); r.onload=()=>setS({...s,logo:r.result}); r.readAsDataURL(f)}; const saveSettings=()=>commit({...db,settings:s}); return <div className="card"><h3><Palette/> Tasarım Ayarları</h3><label>Logo yükle</label><input type="file" accept="image/*" onChange={upload}/>{s.logo&&<div className="previewLogo"><img src={s.logo}/><button className="danger" onClick={()=>setS({...s,logo:''})}>Logoyu Kaldır</button></div>}<label>Uygulama adı</label><input value={s.app_name} onChange={e=>setS({...s,app_name:e.target.value})}/><label>Cafe adı</label><input value={s.cafe_name} onChange={e=>setS({...s,cafe_name:e.target.value})}/><label>Ana ekran başlığı</label><input value={s.hero_title||''} onChange={e=>setS({...s,hero_title:e.target.value})}/><label>Ana ekran açıklaması</label><input value={s.hero_subtitle||''} onChange={e=>setS({...s,hero_subtitle:e.target.value})}/><label>Kampanya mini yazısı</label><input value={s.promo_text||''} onChange={e=>setS({...s,promo_text:e.target.value})}/><div className="formGrid"><div><label>Arka plan</label><input type="color" value={s.bg} onChange={e=>setS({...s,bg:e.target.value})}/></div><div><label>Kart rengi</label><input type="color" value={s.card} onChange={e=>setS({...s,card:e.target.value})}/></div><div><label>Vurgu rengi</label><input type="color" value={s.accent} onChange={e=>setS({...s,accent:e.target.value})}/></div></div><label>Font seçimi</label><select value={s.font} onChange={e=>setS({...s,font:e.target.value})}><option>Inter</option><option>Arial</option><option>Georgia</option><option>Verdana</option><option>Tahoma</option><option>Trebuchet MS</option></select><button onClick={saveSettings}><Save/> Ayarları Kaydet</button></div>}
function ProductAdmin({db,commit}){const imgUpload=e=>{const f=e.target.files?.[0]; if(!f)return; const r=new FileReader(); r.onload=()=>setForm(x=>({...x,image:r.result})); r.readAsDataURL(f)}; const blank={id:null,categoryId:db.categories[0]?.id||1,name:'',description:'',price:'',featured:false,image:'☕',tone:'#b9f5d0'}; const [form,setForm]=useState(blank); const saveItem=()=>{if(!form.name||!form.price)return alert('Ürün adı ve fiyat gir.'); const item={...form,price:Number(form.price),id:form.id||Date.now()}; let items=form.id?db.items.map(i=>i.id===form.id?item:i):[item,...db.items]; commit({...db,items}); setForm(blank)}; const del=id=>{if(confirm('Ürün silinsin mi?'))commit({...db,items:db.items.filter(i=>i.id!==id)})}; return <div className="card"><h3>Ürün Ekle / Düzenle</h3><label>Kategori</label><select value={form.categoryId} onChange={e=>setForm({...form,categoryId:Number(e.target.value)})}>{db.categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><label>Ürün adı</label><input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Örn: Ice Latte"/><label>Açıklama</label><input value={form.description} onChange={e=>setForm({...form,description:e.target.value})} placeholder="Kısa açıklama"/><label>Fiyat</label><input value={form.price} onChange={e=>setForm({...form,price:e.target.value})} inputMode="numeric" placeholder="₺"/><label>Ürün görseli yükle</label><input type="file" accept="image/*" onChange={imgUpload}/><label>Ürün görseli / emoji veya görsel linki</label><input value={form.image||''} onChange={e=>setForm({...form,image:e.target.value})} placeholder="🍔 veya https://... görsel linki"/>{form.image&&<div className="imagePreviewLine"><ProductVisual item={form}/><small>Önizleme</small></div>}<label>Ürün arka plan tonu</label><input type="color" value={form.tone||'#b9f5d0'} onChange={e=>setForm({...form,tone:e.target.value})}/><label className="check"><input type="checkbox" checked={form.featured} onChange={e=>setForm({...form,featured:e.target.checked})}/> Öne çıkanlarda göster</label><button onClick={saveItem}>{form.id?<Pencil/>:<Plus/>} {form.id?'Ürünü Güncelle':'Ürün Ekle'}</button><hr/>{db.categories.map(cat=><div key={cat.id}><h4>{cat.name}</h4>{db.items.filter(i=>i.categoryId===cat.id).map(i=><div className="adminItem" key={i.id}><div><b>{i.name}</b><p>{i.price}₺ · {i.description}</p></div><button className="mini" onClick={()=>setForm(i)}><Pencil size={16}/></button><button className="mini danger" onClick={()=>del(i.id)}><Trash2 size={16}/></button></div>)}</div>)}</div>}
function CustomerAdmin({db}){return <div className="card"><h3>Kayıtlı Kullanıcılar</h3><p>Toplam {db.customers.length} kullanıcı</p>{db.customers.map(c=>{const l=db.loyalty[c.id]||{};return <div className="customerRow" key={c.id}><div><b>{c.name}</b><p>{c.phone} · {c.isAdmin?'Admin':'Müşteri'}</p><small>Kayıt: {c.createdAt||'Eski kayıt'}</small></div><strong>{l.totalStamps||0} damga<br/>{l.availableRewards||0} ödül</strong></div>})}</div>}
function QrScanner({onResult}){const [active,setActive]=useState(false); const [err,setErr]=useState(''); const scannerRef=useRef(null); const boxId='liberte-qr-reader';
 useEffect(()=>()=>{if(scannerRef.current){scannerRef.current.stop().catch(()=>{}); scannerRef.current.clear().catch(()=>{})}},[]);
 const start=async()=>{setErr(''); try{const scanner=new Html5Qrcode(boxId); scannerRef.current=scanner; await scanner.start({facingMode:'environment'},{fps:10,qrbox:{width:240,height:240}},txt=>{onResult(txt); stop();},()=>{}); setActive(true)}catch(e){setErr('Kamera açılamadı. Tarayıcı kamera izni ver veya HTTPS bağlantıdan aç.')} };
 const stop=async()=>{try{if(scannerRef.current){await scannerRef.current.stop(); await scannerRef.current.clear(); scannerRef.current=null}}catch{} setActive(false)};
 return <div className="scannerBox"><div id={boxId}></div>{err&&<p className="errorText">{err}</p>}<button onClick={active?stop:start}>{active?'Kamerayı Kapat':'Kamera ile QR Okut'}</button><small>Canlı sitede kamera çalışır. Telefonda tarayıcı kamera izni istemeli.</small></div>}
function LoyaltyAdmin({db,commit}){const [phone,setPhone]=useState(''); const [msg,setMsg]=useState(''); const [lastQr,setLastQr]=useState(''); const customers=db.customers; const target=customers.find(c=>c.phone===normalize(phone));
 const handleQr=(txt)=>{setLastQr(txt); let ph=''; const parts=String(txt).split(':'); if(parts[0]==='LIBERTE'&&parts[2]) ph=parts[2]; else ph=String(txt).replace(/\D/g,''); if(ph){setPhone(ph); setTimeout(()=>alert('QR okundu. Müşteri bulunduysa damga verebilirsin.'),200)} else alert('QR okunamadı veya Liberte QR formatı değil.')};
 const addStamp=()=>{if(!target)return alert('Müşteri bulunamadı. Önce müşteri kendi telefonuyla giriş yapsın.'); const n={...db,loyalty:{...db.loyalty},history:[...db.history]}; let card={...(n.loyalty[target.id]||{customerId:target.id,totalStamps:0,availableRewards:0,usedRewards:0,lifetimeStamps:0})}; card.totalStamps++; card.lifetimeStamps++; if(card.totalStamps>=n.settings.stamp_threshold){card.totalStamps=0; card.availableRewards++; alert('Tebrikler! Müşteriye ödül oluştu: '+n.settings.reward_description)} n.loyalty[target.id]=card; n.history.unshift({id:Date.now(),type:'stamp',phone:target.phone,date:new Date().toLocaleString('tr-TR')}); commit(n)};
 const removeStamp=()=>{if(!target)return alert('Müşteri bulunamadı.'); const n={...db,loyalty:{...db.loyalty},history:[...db.history]}; let card={...(n.loyalty[target.id]||{customerId:target.id,totalStamps:0,availableRewards:0,usedRewards:0,lifetimeStamps:0})}; card.totalStamps=Math.max(0,(card.totalStamps||0)-1); n.loyalty[target.id]=card; n.history.unshift({id:Date.now(),type:'remove-stamp',phone:target.phone,date:new Date().toLocaleString('tr-TR')}); commit(n)};
 const useReward=()=>{if(!target)return; const n={...db,loyalty:{...db.loyalty},history:[...db.history]}; let card={...n.loyalty[target.id]}; if(!card?.availableRewards)return alert('Hazır ödül yok.'); card.availableRewards--; card.usedRewards++; n.loyalty[target.id]=card; n.history.unshift({id:Date.now(),type:'reward',phone:target.phone,date:new Date().toLocaleString('tr-TR')}); commit(n)};
 const send=async()=>{if(!msg)return; const n={...db,notifications:[{id:Date.now(),title:'Liberte Duyuru',body:msg,createdAt:new Date().toLocaleString('tr-TR')},...db.notifications]}; commit(n); try{if('Notification' in window){let perm=Notification.permission;if(perm==='default') perm=await Notification.requestPermission(); if(perm==='granted') new Notification('Liberte Duyuru',{body:msg});}}catch{} setMsg('')};
 return <><div className="card"><h3><ScanLine/> QR ile Damga Ver</h3><QrScanner onResult={handleQr}/>{lastQr&&<small>Son okunan QR: {lastQr}</small>}<label>Manuel telefon / QR sonrası otomatik dolar</label><input value={phone} onChange={e=>setPhone(e.target.value)} placeholder="Müşteri telefonu" inputMode="tel"/>{target&&<div className="foundCustomer"><b>{target.name}</b><p>{target.phone} · Damga: {db.loyalty[target.id]?.totalStamps||0} · Ödül: {db.loyalty[target.id]?.availableRewards||0}</p></div>}<div className="actions"><button onClick={addStamp}><Plus/> +1 Damga Ekle</button><button onClick={removeStamp} className="secondary"><Minus/> Damga Sil</button></div><button onClick={useReward} className="secondary"><Gift/> Ödül Kullandır</button></div><div className="card"><h3>Bildirim / Kampanya Ekle</h3><textarea value={msg} onChange={e=>setMsg(e.target.value)} placeholder="Örn: Bugüne özel Ice Latte kampanyası..."/><button onClick={send}>Yayınla</button></div><div className="card"><h3>Son İşlemler</h3>{db.history.slice(0,12).map(h=><p key={h.id}>{h.type==='stamp'?'☕ Damga':h.type==='remove-stamp'?'➖ Damga Silindi':'🎁 Ödül'} · {h.phone} · {h.date}</p>)}</div></>}

function CashierAdmin({db,commit}){const [q,setQ]=useState(''); const [quick,setQuick]=useState(null); const customers=db.customers.filter(c=>!q||c.name.toLowerCase().includes(q.toLowerCase())||c.phone.includes(normalize(q))); const addQuick=(customer)=>{const n={...db,loyalty:{...db.loyalty},history:[...db.history]}; let card={...(n.loyalty[customer.id]||{customerId:customer.id,totalStamps:0,availableRewards:0,usedRewards:0,lifetimeStamps:0})}; card.totalStamps++; card.lifetimeStamps++; if(card.totalStamps>=n.settings.stamp_threshold){card.totalStamps=0; card.availableRewards++; setQuick(customer.name+' için ödül oluştu 🎁')}else{setQuick(customer.name+' için +1 damga eklendi')} n.loyalty[customer.id]=card; n.history.unshift({id:Date.now(),type:'cashier-stamp',phone:customer.phone,date:new Date().toLocaleString('tr-TR')}); commit(n)}; return <div className="card cashierCard"><h3><ShoppingBag/> Kasiyer Modu</h3><p>Yoğun saatlerde hızlı damga vermek için kullan.</p>{quick&&<div className="successToast">{quick}</div>}<input value={q} onChange={e=>setQ(e.target.value)} placeholder="Müşteri adı veya telefon ara"/><div className="cashierList">{customers.map(c=>{const l=db.loyalty[c.id]||{};return <div className="cashierRow" key={c.id}><div><b>{c.name}</b><p>{c.phone} · {l.totalStamps||0} damga · {l.availableRewards||0} ödül</p></div><button onClick={()=>addQuick(c)}><Plus/> Damga</button></div>})}</div></div>}

function Nav({tab,setTab,isAdmin}){const b=[['home',Home,'Ana Sayfa'],['qr',QrCode,'QR'],['menu',MenuIcon,'Menü'],['campaign',Bell,'Duyuru']]; if(isAdmin)b.push(['admin',ScanLine,'Admin']); return <nav>{b.map(([id,Icon,label])=><button key={id} className={tab===id?'on':''} onClick={()=>setTab(id)}><Icon size={20}/><span>{label}</span></button>)}</nav>}

createRoot(document.getElementById('root')).render(<App/>);
